version: "3.5"

networks:
  proxy:
    name: ${TRAEFIK_NETWORK_NAME}
    external: true
  internal:

volumes:
  wordpress:
  mysqldir:

services:
  wp:
    build:
      context: .
      dockerfile: Dockerfile.wp
      args:
        PLUGINS: redis-cache,wp-force-login
    networks:
      - proxy
      - internal
    depends_on:
      - db
      - smtp
      - redis
    restart: always
    volumes:
      - wordpress:/var/www/html/wp-content
      - ./php.ini:/usr/local/etc/php/php.ini
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: ${MYSQL_DB_USER}
      WORDPRESS_DB_PASSWORD: ${MYSQL_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: define('WP_REDIS_HOST', 'redis');
    labels:
      - "traefik.docker.network=proxy"
      - "traefik.enable=true"
      - "traefik.basic.frontend.rule=Host:${DOMAIN_NAME}"
      - "traefik.basic.port=80"
      - "traefik.basic.protocol=http"
      - "traefik.frontend.headers.forceSTSHeader=true"
      - "traefik.frontend.headers.STSSeconds=315360000"
      - "traefik.frontend.headers.STSIncludeSubdomains=true"
      - "traefik.frontend.headers.STSPreload=true"

  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: "wordpress"
      MYSQL_USER: ${MYSQL_DB_USER}
      MYSQL_PASSWORD: ${MYSQL_DB_PASSWORD}
    restart: always
    volumes:
      - mysqldir:/var/lib/mysql
    networks:
      - internal
    labels:
      - traefik.enable=false

  smtp:
    image: namshi/smtp
    restart: always
    networks:
      - internal
    labels:
      - traefik.enable=false

  # Auto-update containers.
  watchtower:
    image: v2tec/watchtower:latest
    # Apply updates at midnight.
    command: --cleanup --schedule "0 0 0 * * *"
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=false"

  redis:
    image: redis:alpine
    restart: always
    networks:
      - internal
